require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CensusDatesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # CensusDate. As you add validations to CensusDate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CensusDatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all census_dates as @census_dates" do
      census_date = CensusDate.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:census_dates)).to eq([census_date])
    end
  end

  describe "GET #show" do
    it "assigns the requested census_date as @census_date" do
      census_date = CensusDate.create! valid_attributes
      get :show, {:id => census_date.to_param}, valid_session
      expect(assigns(:census_date)).to eq(census_date)
    end
  end

  describe "GET #new" do
    it "assigns a new census_date as @census_date" do
      get :new, {}, valid_session
      expect(assigns(:census_date)).to be_a_new(CensusDate)
    end
  end

  describe "GET #edit" do
    it "assigns the requested census_date as @census_date" do
      census_date = CensusDate.create! valid_attributes
      get :edit, {:id => census_date.to_param}, valid_session
      expect(assigns(:census_date)).to eq(census_date)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new CensusDate" do
        expect {
          post :create, {:census_date => valid_attributes}, valid_session
        }.to change(CensusDate, :count).by(1)
      end

      it "assigns a newly created census_date as @census_date" do
        post :create, {:census_date => valid_attributes}, valid_session
        expect(assigns(:census_date)).to be_a(CensusDate)
        expect(assigns(:census_date)).to be_persisted
      end

      it "redirects to the created census_date" do
        post :create, {:census_date => valid_attributes}, valid_session
        expect(response).to redirect_to(CensusDate.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved census_date as @census_date" do
        post :create, {:census_date => invalid_attributes}, valid_session
        expect(assigns(:census_date)).to be_a_new(CensusDate)
      end

      it "re-renders the 'new' template" do
        post :create, {:census_date => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested census_date" do
        census_date = CensusDate.create! valid_attributes
        put :update, {:id => census_date.to_param, :census_date => new_attributes}, valid_session
        census_date.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested census_date as @census_date" do
        census_date = CensusDate.create! valid_attributes
        put :update, {:id => census_date.to_param, :census_date => valid_attributes}, valid_session
        expect(assigns(:census_date)).to eq(census_date)
      end

      it "redirects to the census_date" do
        census_date = CensusDate.create! valid_attributes
        put :update, {:id => census_date.to_param, :census_date => valid_attributes}, valid_session
        expect(response).to redirect_to(census_date)
      end
    end

    context "with invalid params" do
      it "assigns the census_date as @census_date" do
        census_date = CensusDate.create! valid_attributes
        put :update, {:id => census_date.to_param, :census_date => invalid_attributes}, valid_session
        expect(assigns(:census_date)).to eq(census_date)
      end

      it "re-renders the 'edit' template" do
        census_date = CensusDate.create! valid_attributes
        put :update, {:id => census_date.to_param, :census_date => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested census_date" do
      census_date = CensusDate.create! valid_attributes
      expect {
        delete :destroy, {:id => census_date.to_param}, valid_session
      }.to change(CensusDate, :count).by(-1)
    end

    it "redirects to the census_dates list" do
      census_date = CensusDate.create! valid_attributes
      delete :destroy, {:id => census_date.to_param}, valid_session
      expect(response).to redirect_to(census_dates_url)
    end
  end

end
